# --- RUST CONFIGURATION ---
[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config]
checkOnSave = true
cargo = { loadOutDirsFromCheck = true }
procMacro = { enable = true }

# --- PYTHON CONFIGURATION ---
[[language]]
name = "python"
auto-format = true
language-servers = ["pyright", "ruff"] # Uses pyright for types/autocomplete and ruff for diagnostics

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]

# --- RUBY CONFIGURATION ---
[[language]]
name = "ruby"
auto-format = true
language-servers = ["ruby-lsp", "solargraph"] # Uses ruby-lsp for linting/formatting and Solargraph for other

[language-server.solargraph]
command = "solargraph"
args = ["stdio"]
config = { diagnostics = false, formatting = false }

[language-server.ruby-lsp]
command = "ruby-lsp"
args = ["stdio"]
config = { diagnostics = true, formatting = true }
